#!/usr/bin/env python3
"""
Minimal Example — Run Script

Demonstrates running an AEROSPACEMODEL transformation programmatically.
"""

import sys
from pathlib import Path

# Add src to path for development
example_dir = Path(__file__).parent
repo_root = example_dir.parent.parent
sys.path.insert(0, str(repo_root / "src"))

def main():
    """Run the minimal example transformation."""
    
    print("=" * 70)
    print("AEROSPACEMODEL — Minimal Example")
    print("=" * 70)
    print()
    
    # Configuration
    contract_id = "DEMO-CTR-AMM-001"
    baseline_id = "DBL-DEMO-001"
    
    print(f"Contract:  {contract_id}")
    print(f"Baseline:  {baseline_id}")
    print()
    
    try:
        # Import the AEROSPACEMODEL engine
        from aerospacemodel.asigt.engine import TransformationEngine
        from aerospacemodel.asit.contracts import ContractLoader
        from aerospacemodel.asit.baselines import BaselineManager
        
        # Load contract
        print("[1/5] Loading contract...")
        contract_loader = ContractLoader(example_dir / "ASIT" / "CONTRACTS")
        contract = contract_loader.load(contract_id)
        print(f"      ✓ Contract loaded: {contract.title}")
        
        # Validate baseline
        print("[2/5] Validating baseline...")
        baseline_mgr = BaselineManager(example_dir / "ASIT" / "GOVERNANCE")
        baseline = baseline_mgr.get(baseline_id)
        print(f"      ✓ Baseline valid: {baseline.name}")
        
        # Initialize engine
        print("[3/5] Initializing ASIGT engine...")
        engine = TransformationEngine(
            config_path=example_dir / "program_config.yaml",
            contract=contract,
            baseline=baseline
        )
        print("      ✓ Engine initialized")
        
        # Execute transformation
        print("[4/5] Executing transformation...")
        result = engine.execute()
        print(f"      ✓ Generated {result.dm_count} Data Module(s)")
        
        # Generate report
        print("[5/5] Generating reports...")
        engine.generate_reports()
        print(f"      ✓ Reports saved to: ASIGT/runs/{result.run_id}/")
        
        print()
        print("=" * 70)
        print("SUCCESS — Transformation complete!")
        print("=" * 70)
        print()
        print("Output locations:")
        print(f"  • Data Modules: IDB/csdb/dms/")
        print(f"  • Trace Matrix: ASIGT/runs/{result.run_id}/TRACE_MATRIX.csv")
        print(f"  • Validation:   ASIGT/runs/{result.run_id}/VALIDATION_REPORT.json")
        print()
        
        return 0
        
    except ImportError as e:
        print()
        print("Note: AEROSPACEMODEL package not installed.")
        print("This script demonstrates the programmatic interface.")
        print()
        print("To run this example:")
        print("  1. Install the package: pip install -e .")
        print("  2. Or use the CLI: aerospacemodel run --contract DEMO-CTR-AMM-001")
        print()
        print(f"Import error: {e}")
        print()
        
        # Demo mode - show what would happen
        print("-" * 70)
        print("DEMO MODE — Simulating transformation")
        print("-" * 70)
        print()
        
        demo_transformation()
        
        return 0
        
    except Exception as e:
        print()
        print(f"ERROR: {e}")
        print()
        return 1


def demo_transformation():
    """Simulate transformation for demo purposes."""
    
    import json
    from datetime import datetime
    
    # Create output directories
    run_id = datetime.now().strftime("%Y%m%d-%H%M") + "__DEMO-CTR-AMM-001"
    
    runs_dir = example_dir / "ASIGT" / "runs" / run_id
    runs_dir.mkdir(parents=True, exist_ok=True)
    
    idb_dir = example_dir / "IDB" / "csdb" / "dms"
    idb_dir.mkdir(parents=True, exist_ok=True)
    
    output_dir = example_dir / "output"
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Create sample Data Module
    dm_code = "DMC-DEMO-A-28-00-00-00A-040A-A"
    dm_filename = f"{dm_code}_001-00.xml"
    
    dm_content = '''<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by AEROSPACEMODEL (Demo Mode)
  Contract: DEMO-CTR-AMM-001
  Baseline: DBL-DEMO-001
-->
<dmodule xmlns="http://www.s1000d.org/S1000D_5-0">
  <identAndStatusSection>
    <dmAddress>
      <dmIdent>
        <dmCode modelIdentCode="DEMO" systemDiffCode="A" 
                systemCode="28" subSystemCode="0" subSubSystemCode="0"
                assyCode="00" disassyCode="00" disassyCodeVariant="A"
                infoCode="040" infoCodeVariant="A" itemLocationCode="A"/>
        <language languageIsoCode="en" countryIsoCode="US"/>
        <issueInfo issueNumber="001" inWork="00"/>
      </dmIdent>
      <dmAddressItems>
        <issueDate year="2026" month="01" day="22"/>
        <dmTitle>
          <techName>Fuel system</techName>
          <infoName>Description</infoName>
        </dmTitle>
      </dmAddressItems>
    </dmAddress>
    <dmStatus>
      <security securityClassification="01"/>
      <responsiblePartnerCompany>
        <enterpriseIdent manufacturerCodeValue="DEMO1"/>
      </responsiblePartnerCompany>
      <originator>
        <enterpriseIdent manufacturerCodeValue="DEMO1"/>
      </originator>
      <brexDmRef>
        <dmRef>
          <dmRefIdent>
            <dmCode modelIdentCode="S1000D" systemDiffCode="G"
                    systemCode="04" subSystemCode="1" subSubSystemCode="0"
                    assyCode="03" disassyCode="01" disassyCodeVariant="A"
                    infoCode="022" infoCodeVariant="A" itemLocationCode="D"/>
          </dmRefIdent>
        </dmRef>
      </brexDmRef>
    </dmStatus>
  </identAndStatusSection>
  <content>
    <description>
      <levelledPara>
        <title>General</title>
        <para>The fuel system provides storage, management, and delivery 
        of fuel to the aircraft engines.</para>
      </levelledPara>
      <levelledPara>
        <title>System Components</title>
        <para>The fuel system consists of:</para>
        <randomList>
          <listItem>
            <para>Fuel tanks (wing and center)</para>
          </listItem>
          <listItem>
            <para>Fuel pumps (boost and transfer)</para>
          </listItem>
          <listItem>
            <para>Fuel quantity indication system</para>
          </listItem>
          <listItem>
            <para>Fuel distribution manifold</para>
          </listItem>
        </randomList>
      </levelledPara>
    </description>
  </content>
</dmodule>
'''
    
    (idb_dir / dm_filename).write_text(dm_content, encoding="utf-8")
    print(f"  ✓ Created: IDB/csdb/dms/{dm_filename}")
    
    # Create trace matrix
    trace_content = '''trace_id,source_type,source_id,target_type,target_id,relationship,verified
TRACE-001,requirement,REQ-FUEL-001,dm,DMC-DEMO-A-28-00-00-00A-040A-A,satisfies,true
'''
    (runs_dir / "TRACE_MATRIX.csv").write_text(trace_content, encoding="utf-8")
    print(f"  ✓ Created: ASIGT/runs/{run_id}/TRACE_MATRIX.csv")
    
    # Create validation report
    validation = {
        "run_id": run_id,
        "contract_id": "DEMO-CTR-AMM-001",
        "baseline_id": "DBL-DEMO-001",
        "timestamp": datetime.now().isoformat(),
        "validators": {
            "brex": {
                "status": "pass",
                "rules_checked": 5,
                "violations": 0,
                "warnings": 0
            },
            "trace": {
                "status": "pass",
                "sources_traced": 1,
                "orphans": 0
            }
        },
        "overall_status": "pass"
    }
    (runs_dir / "VALIDATION_REPORT.json").write_text(
        json.dumps(validation, indent=2), encoding="utf-8"
    )
    print(f"  ✓ Created: ASIGT/runs/{run_id}/VALIDATION_REPORT.json")
    
    # Create metrics
    metrics = {
        "run_id": run_id,
        "duration_seconds": 0.5,
        "sources_processed": 1,
        "dms_generated": 1,
        "dms_validated": 1,
        "validation_pass_rate": 1.0
    }
    (runs_dir / "METRICS.json").write_text(
        json.dumps(metrics, indent=2), encoding="utf-8"
    )
    print(f"  ✓ Created: ASIGT/runs/{run_id}/METRICS.json")
    
    print()
    print("Demo transformation complete!")
    print()
    print("Generated files:")
    print(f"  • IDB/csdb/dms/{dm_filename}")
    print(f"  • ASIGT/runs/{run_id}/TRACE_MATRIX.csv")
    print(f"  • ASIGT/runs/{run_id}/VALIDATION_REPORT.json")
    print(f"  • ASIGT/runs/{run_id}/METRICS.json")


if __name__ == "__main__":
    sys.exit(main())
