# =============================================================================
# Constellation 3D Mesh Pipeline
# =============================================================================
#
# This pipeline defines the data flow across a governed 3D mesh topology
# for satellite constellation operations under AEROSPACEMODEL governance.
#
# Architecture:
#   The pipeline operates on three axes:
#   - Axis 1: Data Lifecycle (generation → classification → transmission →
#             processing → consumption)
#   - Axis 2: 3D Mesh Topology (intra-orbit, inter-orbit, cross-layer,
#             ground links)
#   - Axis 3: Functional Layers (core mission, ATM/CNS, military/security,
#             ground-based)
#
# Key Principles:
#   - No data flows without governance classification
#   - QoS-driven routing across the mesh
#   - Multi-path and disjoint-path resilience
#   - Physics-anchored model constraints (orbital dynamics, link budget)
#   - Distributed cognition: micro-models on-board, federated in-network,
#     foundation models on ground
#
# =============================================================================

pipeline:
  id: "CONSTELLATION-MESH-001"
  name: "Constellation 3D Mesh Data Pipeline"
  version: "1.0.0"
  description: |
    End-to-end data pipeline for governed satellite constellation
    operations. Manages data from on-board generation through mesh
    routing to ground consumption, with distributed AI processing
    at every tier.

  # Metadata
  metadata:
    author: "AEROSPACEMODEL"
    created: "2026-02-07"
    compliance:
      - "S1000D Issue 5.0"
      - "DO-178C traceability"
      - "ARP4761 safety assessment"
    deterministic: true
    replayable: true

  # ═══════════════════════════════════════════════════════════════════════
  # TOPOLOGY CONFIGURATION
  # ═══════════════════════════════════════════════════════════════════════

  topology:
    type: "mesh_3d"
    description: "Multi-layer 3D mesh with TSU-based redundancy"

    orbital_layers:
      - layer: "LEO"
        altitude_range_km: [400, 1200]
        link_types: ["INTRA_ORBIT", "INTER_ORBIT"]
      - layer: "MEO"
        altitude_range_km: [2000, 35786]
        link_types: ["INTRA_ORBIT", "CROSS_LAYER"]
      - layer: "GEO"
        altitude_range_km: [35786, 35786]
        link_types: ["CROSS_LAYER", "GROUND_DOWNLINK"]
      - layer: "GROUND"
        link_types: ["GROUND_UPLINK", "GROUND_DOWNLINK"]

    tsu_configuration:
      redundancy_level: 2
      min_k_connectivity: 2
      single_point_of_failure_check: true
      auto_reconfiguration: true

    properties:
      k_connectivity: 2
      multi_path_routing: true
      disjoint_path_routing: true
      auto_reconfiguration: true

  # ═══════════════════════════════════════════════════════════════════════
  # FUNCTIONAL LAYERS
  # ═══════════════════════════════════════════════════════════════════════

  functional_layers:
    core_mission:
      description: "Primary mission data (EO, communications, navigation)"
      mission_types:
        - "earth_observation"
        - "communications"
        - "navigation"

    atm_cns:
      description: "Air Traffic Management / CNS critical tenant"
      services:
        - "ADS_B_SURVEILLANCE"
        - "VHF_COMMUNICATIONS"
        - "VDL_DATALINK"
        - "CNS_NAVIGATION"
      qos:
        max_latency_ms: 150
        max_jitter_ms: 20
        min_availability: 0.9999
        redundant_paths: 2

    military_security:
      description: "Military and security overlay"
      encryption:
        levels: ["LINK", "NETWORK", "APPLICATION"]
        compartmentalized: true
        key_rotation_hours: 12
      crypto_domains:
        - domain_id: "CIVIL"
          name: "Civil operations"
        - domain_id: "DUAL_USE"
          name: "Dual-use operations"
        - domain_id: "MILITARY"
          name: "Military operations"

    ground_based:
      description: "Ground segment (MOC/SOC, gateways, data centers)"
      redundancy_mode: "ACTIVE_ACTIVE"
      segments:
        - type: "MOC"
          description: "Mission Operations Center"
        - type: "SOC"
          description: "Satellite Operations Center"
        - type: "DATA_CENTER"
          description: "Data processing and archive"

  # ═══════════════════════════════════════════════════════════════════════
  # DATA LIFECYCLE STAGES
  # ═══════════════════════════════════════════════════════════════════════

  data_lifecycle:
    stages:
      - stage: "GENERATION"
        description: "On-board data generation"
        data_origins:
          - "TELEMETRY"
          - "HOUSEKEEPING"
          - "PAYLOAD_EO"
          - "PAYLOAD_COMMS"
          - "PAYLOAD_NAV"
          - "ATM_SURVEILLANCE"
          - "SECURITY_EVENT"
          - "ANOMALY_DETECTION"

      - stage: "CLASSIFICATION"
        description: "Data classification and metadata tagging"
        data_classes:
          - class: "CRITICAL_REALTIME"
            priority: 1
            deadline_ms: 100
          - class: "NEAR_REALTIME"
            priority: 2
            deadline_ms: 1000
          - class: "BULK_DEFERRABLE"
            priority: 5
          - class: "ATM"
            priority: 1
            deadline_ms: 150
          - class: "MILITARY"
            priority: 2
            deadline_ms: 500
          - class: "SECURITY"
            priority: 1
            deadline_ms: 200

      - stage: "TRANSMISSION"
        description: "QoS-driven routing through the 3D mesh"
        routing_policies:
          critical_realtime:
            use_multipath: true
            use_disjoint_paths: true
          bulk_deferrable:
            opportunistic: true
            use_spare_capacity: true

      - stage: "PROCESSING"
        description: "Multi-tier processing (on-board, in-network, ground)"
        locations:
          on_board:
            operations:
              - "edge_ai_inference"
              - "semantic_compression"
              - "anomaly_detection"
              - "local_control"
          in_network:
            operations:
              - "collaborative_inference"
              - "federated_aggregation"
              - "intelligent_caching"
          ground:
            operations:
              - "deep_analysis"
              - "model_retraining"
              - "archive_analytics"

      - stage: "CONSUMPTION"
        description: "Data consumption and feedback actions"
        actions:
          - "CONSTELLATION_CONTROL"
          - "MISSION_CONTROL"
          - "ATM_SERVICE"
          - "DEFENSE_SERVICE"
          - "OBSERVATION_SERVICE"
          - "SPACE_WEATHER"
          - "MODEL_UPDATE"
          - "POLICY_UPDATE"

  # ═══════════════════════════════════════════════════════════════════════
  # COGNITIVE LAYER (Distributed Model Field)
  # ═══════════════════════════════════════════════════════════════════════

  cognitive:
    description: |
      AEROSPACEMODEL is the neural network built from data flows
      circulating in a governed, multidimensional, multipurpose topology.

    model_tiers:
      micro:
        location: "on_board"
        capabilities:
          - "ANOMALY_DETECTION"
          - "SEMANTIC_COMPRESSION"
          - "LOCAL_CONTROL"
          - "EDGE_INFERENCE"
        physics_constraints:
          - type: "POWER_BUDGET"
            max_power_w: 50.0
          - type: "ORBITAL_DYNAMICS"
            description: "Model must account for orbital mechanics"

      in_network:
        location: "constellation"
        capabilities:
          - "COLLABORATIVE_INFERENCE"
          - "FEDERATED_AGGREGATION"
          - "INTELLIGENT_CACHING"
        federated_learning:
          enabled: true
          min_participants: 3
          consensus_required: true

      foundation:
        location: "ground"
        capabilities:
          - "DEEP_ANALYSIS"
          - "RETRAINING"
          - "ARCHIVE_ANALYTICS"
        physics_informed: true
        retrain_with_global_history: true

    governance_as_regularizer:
      description: |
        Data governance acts as a regularizer for the model field:
        what is shared, with whom, at what precision, under what encryption.
      sharing_policies: true
      traffic_prioritization: true
      contribution_control: true
