# =============================================================================
# Certification Documentation Pipeline
# Digital Twin Integration — Regulatory Evidence Generation
# Version: 1.0.0
# =============================================================================
#
# This pipeline generates certification evidence packages required for
# regulatory compliance, including airworthiness directives and type
# certification documentation.
#
# Request Types:
#   - Type Certification evidence
#   - Airworthiness Directive compliance
#   - Continued Airworthiness documentation
#   - Design change approval packages
#
# Output Types:
#   - Compliance matrices
#   - Test evidence packages
#   - Traceability reports
#   - Certification summaries
#
# =============================================================================

pipeline:
  metadata:
    pipeline_id: "PIPELINE-DT-CERT-001"
    name: "Certification Documentation Pipeline"
    description: |
      Generates certification evidence packages for regulatory compliance.
      Produces compliance matrices, test evidence, and traceability
      documentation with digital twin data provenance.
    version: "1.0.0"
    publication_type: "CERT"
    s1000d_issue: "5.0"
    
    owner: "Certification Engineering"
    maintainer: "Publication Engineering"
    
    created: "2026-01-22"
    last_modified: "2026-01-22"
    
    tags:
      - "digital-twin"
      - "certification"
      - "compliance"
      - "evidence"
      - "regulatory"

  # ---------------------------------------------------------------------------
  # TRIGGER CONFIGURATION
  # ---------------------------------------------------------------------------
  triggers:
    type: "certification_request"
    
    request_types:
      - request_type: "TYPE_CERTIFICATION"
        name: "Type Certification Submission"
        priority: "critical"
        evidence_level: "comprehensive"
        
      - request_type: "AIRWORTHINESS_DIRECTIVE"
        name: "Airworthiness Directive Compliance"
        priority: "critical"
        evidence_level: "full"
        
      - request_type: "CONTINUED_AIRWORTHINESS"
        name: "Continued Airworthiness Review"
        priority: "high"
        evidence_level: "standard"
        
      - request_type: "DESIGN_CHANGE"
        name: "Design Change Approval"
        priority: "high"
        evidence_level: "targeted"

  # ---------------------------------------------------------------------------
  # CONTRACT BINDING
  # ---------------------------------------------------------------------------
  contract:
    template: "ASIT/CONTRACTS/templates/DT-CTR-CERT.template.yaml"
    
    required_fields:
      - "contract_id"
      - "baseline_ref"
      - "certification_request"
      - "regulatory_reference"
      - "scope.ata_chapters"
      - "authority.approved_by"
      - "authority.certification_manager"
    
    validation:
      check_baseline_exists: true
      check_authority_valid: true
      check_regulatory_reference: true
      require_certification_manager: true

  # ---------------------------------------------------------------------------
  # PIPELINE STAGES
  # ---------------------------------------------------------------------------
  stages:
    # -------------------------------------------------------------------------
    # STAGE 1: CERTIFICATION CONTEXT
    # -------------------------------------------------------------------------
    - stage: "certification_context"
      name: "Establish Certification Context"
      description: "Parse certification request and establish evidence requirements"
      order: 1
      
      steps:
        - step: "parse_certification_request"
          name: "Parse Certification Request"
          action: "cert.parse_request"
          inputs:
            request_data: "${certification_request}"
            request_types: "${pipeline.triggers.request_types}"
          outputs:
            - "parsed_request"
            - "evidence_requirements"
          on_failure: "abort"
          
        - step: "load_regulatory_requirements"
          name: "Load Regulatory Requirements"
          action: "cert.load_regulatory"
          inputs:
            regulatory_reference: "${parsed_request.regulatory_reference}"
            regulation_database: "KDB/regulations/"
          outputs:
            - "regulatory_requirements"
            - "compliance_criteria"
          on_failure: "abort"
          
        - step: "determine_evidence_scope"
          name: "Determine Evidence Scope"
          action: "cert.determine_scope"
          inputs:
            parsed_request: "${parsed_request}"
            regulatory_requirements: "${regulatory_requirements}"
            evidence_requirements: "${evidence_requirements}"
          outputs:
            - "evidence_scope"
            - "required_artifacts"
            - "ata_chapters"
          on_failure: "abort"

    # -------------------------------------------------------------------------
    # STAGE 2: SOURCE COLLECTION
    # -------------------------------------------------------------------------
    - stage: "source_collection"
      name: "Collect Evidence Sources"
      description: "Gather all source materials for certification evidence"
      order: 2
      depends_on: ["certification_context"]
      
      steps:
        - step: "load_requirements"
          name: "Load Design Requirements"
          action: "source.load"
          inputs:
            source_type: "requirement"
            source_paths:
              - "KDB/requirements"
          outputs:
            - "design_requirements"
          filters:
            - field: "ata_chapter"
              operator: "in"
              values: "${ata_chapters}"
            - field: "certification_relevant"
              values: [true]
          on_failure: "warn"
          
        - step: "load_test_evidence"
          name: "Load Test Evidence"
          action: "source.load"
          inputs:
            source_type: "test_evidence"
            source_paths:
              - "KDB/test_evidence"
          outputs:
            - "test_evidence"
          filters:
            - field: "ata_chapter"
              operator: "in"
              values: "${ata_chapters}"
          on_failure: "warn"
          
        - step: "load_digital_twin_records"
          name: "Load Digital Twin Records"
          action: "dt.load_certification_records"
          inputs:
            source_path: "KDB/system_data"
            scope: "${evidence_scope}"
          outputs:
            - "dt_records"
            - "data_provenance"
          on_failure: "warn"
          
        - step: "load_maintenance_data"
          name: "Load Maintenance Instructions"
          action: "source.load"
          inputs:
            source_type: "task"
            source_paths:
              - "KDB/tasks"
          outputs:
            - "maintenance_instructions"
          filters:
            - field: "ata_chapter"
              operator: "in"
              values: "${ata_chapters}"
            - field: "publication"
              values: ["AMM", "CMM", "ALL"]
          on_failure: "warn"

    # -------------------------------------------------------------------------
    # STAGE 3: COMPLIANCE ANALYSIS
    # -------------------------------------------------------------------------
    - stage: "compliance_analysis"
      name: "Analyze Compliance"
      description: "Analyze evidence against compliance criteria"
      order: 3
      depends_on: ["source_collection"]
      
      steps:
        - step: "build_compliance_matrix"
          name: "Build Compliance Matrix"
          action: "cert.build_compliance_matrix"
          inputs:
            regulatory_requirements: "${regulatory_requirements}"
            compliance_criteria: "${compliance_criteria}"
            design_requirements: "${design_requirements}"
            test_evidence: "${test_evidence}"
            maintenance_instructions: "${maintenance_instructions}"
          outputs:
            - "compliance_matrix"
            - "compliance_gaps"
          on_failure: "abort"
          
        - step: "analyze_coverage"
          name: "Analyze Evidence Coverage"
          action: "cert.analyze_coverage"
          inputs:
            compliance_matrix: "${compliance_matrix}"
            required_artifacts: "${required_artifacts}"
          outputs:
            - "coverage_analysis"
            - "missing_evidence"
          on_failure: "warn"
          
        - step: "validate_traceability"
          name: "Validate End-to-End Traceability"
          action: "cert.validate_traceability"
          inputs:
            design_requirements: "${design_requirements}"
            test_evidence: "${test_evidence}"
            maintenance_instructions: "${maintenance_instructions}"
            dt_records: "${dt_records}"
          outputs:
            - "traceability_report"
            - "trace_gaps"
          on_failure: "warn"

    # -------------------------------------------------------------------------
    # STAGE 4: EVIDENCE GENERATION
    # -------------------------------------------------------------------------
    - stage: "evidence_generation"
      name: "Generate Certification Evidence"
      description: "Generate formal certification evidence documents"
      order: 4
      depends_on: ["compliance_analysis"]
      
      steps:
        - step: "generate_compliance_matrix_doc"
          name: "Generate Compliance Matrix Document"
          action: "generator.compliance_matrix"
          inputs:
            compliance_matrix: "${compliance_matrix}"
            regulatory_requirements: "${regulatory_requirements}"
            template: "templates/compliance_matrix.xml"
            config:
              model_ident_code: "${config.model_ident_code}"
              include_evidence_links: true
              include_status: true
          outputs:
            - "compliance_matrix_doc"
          on_failure: "abort"
          
        - step: "generate_test_evidence_package"
          name: "Generate Test Evidence Package"
          action: "generator.evidence_package"
          inputs:
            test_evidence: "${test_evidence}"
            compliance_matrix: "${compliance_matrix}"
            template: "templates/evidence_package.xml"
            config:
              model_ident_code: "${config.model_ident_code}"
              include_test_reports: true
              include_data_sheets: true
          outputs:
            - "test_evidence_package"
          on_failure: "continue"
          
        - step: "generate_traceability_report"
          name: "Generate Traceability Report"
          action: "generator.traceability_report"
          inputs:
            traceability_report: "${traceability_report}"
            compliance_matrix: "${compliance_matrix}"
            data_provenance: "${data_provenance}"
            template: "templates/traceability_report.xml"
            config:
              model_ident_code: "${config.model_ident_code}"
              include_digital_twin_data: true
          outputs:
            - "traceability_doc"
          on_failure: "continue"
          
        - step: "generate_certification_summary"
          name: "Generate Certification Summary"
          action: "generator.certification_summary"
          inputs:
            compliance_matrix: "${compliance_matrix}"
            coverage_analysis: "${coverage_analysis}"
            regulatory_requirements: "${regulatory_requirements}"
            template: "templates/certification_summary.xml"
            config:
              model_ident_code: "${config.model_ident_code}"
          outputs:
            - "certification_summary"
          on_failure: "abort"
          
        - step: "add_certification_metadata"
          name: "Add Certification Metadata"
          action: "cert.add_metadata"
          inputs:
            documents:
              - "${compliance_matrix_doc}"
              - "${test_evidence_package}"
              - "${traceability_doc}"
              - "${certification_summary}"
            certification_request: "${parsed_request}"
            regulatory_reference: "${regulatory_requirements}"
            data_provenance: "${data_provenance}"
          outputs:
            - "certified_documents"
          on_failure: "warn"

    # -------------------------------------------------------------------------
    # STAGE 5: VALIDATION
    # -------------------------------------------------------------------------
    - stage: "validation"
      name: "Certification Validation"
      description: "Validate certification package completeness and integrity"
      order: 5
      depends_on: ["evidence_generation"]
      
      steps:
        - step: "validate_completeness"
          name: "Validate Package Completeness"
          action: "validator.cert_completeness"
          inputs:
            certified_documents: "${certified_documents}"
            required_artifacts: "${required_artifacts}"
            evidence_requirements: "${evidence_requirements}"
          outputs:
            - "completeness_results"
          on_failure: "warn"
          
        - step: "validate_consistency"
          name: "Validate Document Consistency"
          action: "validator.cert_consistency"
          inputs:
            certified_documents: "${certified_documents}"
            compliance_matrix: "${compliance_matrix}"
          outputs:
            - "consistency_results"
          on_failure: "warn"
          
        - step: "compute_package_hash"
          name: "Compute Package Hash"
          action: "hash.compute"
          inputs:
            artifacts: "${certified_documents}"
            algorithm: "sha256"
          outputs:
            - "package_hash"
            - "individual_hashes"
          on_failure: "abort"

    # -------------------------------------------------------------------------
    # STAGE 6: FINALIZATION
    # -------------------------------------------------------------------------
    - stage: "finalization"
      name: "Finalize Certification Package"
      description: "Package and seal certification evidence"
      order: 6
      depends_on: ["validation"]
      always_run: true
      
      steps:
        - step: "assemble_certification_package"
          name: "Assemble Certification Package"
          action: "package.certification"
          inputs:
            certified_documents: "${certified_documents}"
            package_hash: "${package_hash}"
            output_path: "IDB/certification"
          outputs:
            - "certification_package"
          on_failure: "warn"
          
        - step: "generate_submission_manifest"
          name: "Generate Submission Manifest"
          action: "cert.generate_manifest"
          inputs:
            certification_package: "${certification_package}"
            individual_hashes: "${individual_hashes}"
            certification_request: "${parsed_request}"
            output_path: "output/CERTIFICATION_MANIFEST.json"
          outputs:
            - "submission_manifest"
          on_failure: "warn"
          
        - step: "generate_certification_report"
          name: "Generate Certification Status Report"
          action: "report.certification"
          inputs:
            completeness_results: "${completeness_results}"
            consistency_results: "${consistency_results}"
            coverage_analysis: "${coverage_analysis}"
            compliance_gaps: "${compliance_gaps}"
            output_path: "output/reports/CERTIFICATION_STATUS_REPORT.json"
          outputs:
            - "certification_report"
          on_failure: "warn"
          
        - step: "archive_evidence"
          name: "Archive Evidence Package"
          action: "archive.certification"
          inputs:
            certification_package: "${certification_package}"
            submission_manifest: "${submission_manifest}"
            retention_policy: "permanent"
          outputs:
            - "archive_status"
          on_failure: "warn"

  # ---------------------------------------------------------------------------
  # OUTPUTS
  # ---------------------------------------------------------------------------
  outputs:
    primary:
      - name: "Compliance Matrix"
        path: "IDB/certification/compliance"
        type: "compliance_matrix"
        
      - name: "Test Evidence Package"
        path: "IDB/certification/evidence"
        type: "evidence_package"
        
      - name: "Traceability Report"
        path: "IDB/certification/traceability"
        type: "traceability_report"
        
      - name: "Certification Summary"
        path: "IDB/certification/summary"
        type: "certification_summary"
        
    artifacts:
      - name: "Submission Manifest"
        path: "output/CERTIFICATION_MANIFEST.json"
        type: "manifest"
        
      - name: "Certification Status Report"
        path: "output/reports/CERTIFICATION_STATUS_REPORT.json"
        type: "report"
        
      - name: "Package Hash"
        path: "output/PACKAGE_HASH.txt"
        type: "integrity"

  # ---------------------------------------------------------------------------
  # CONFIGURATION
  # ---------------------------------------------------------------------------
  config:
    execution:
      parallel_enabled: false  # Sequential for certification integrity
      timeout_minutes: 120
      
    integrity:
      require_signed_hash: true
      archive_immediately: true
      
    retention:
      policy: "permanent"
      backup_copies: 3
